import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-card-product',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './card-product.component.html',
  styleUrl: './card-product.component.css'
})
export class CardProductComponent {
products: { id: number, link:string, nameProduct: string, description: string, dimensions: string, stock:number, nationality: string, maker: string,price:number,img:string,status:boolean }[] = [
    { id: 1, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 2, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 3, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status: false },
    { id: 4, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 5, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 6, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 7, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status: false },
    { id: 8, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 9, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 10, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 11, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 12, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status: false },
    { id: 13, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 14, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 15, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 16, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 17, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 18, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status: false },
    { id: 19, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 20, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 21, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 22, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 23, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 24, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status: false },
    { id: 25, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 26, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
    { id: 27, link:"https://www.google.com/?hl=es",nameProduct: 'Nombre del producto', description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, at.", dimensions: "HighxWidth", stock:300, nationality: "Colombiano", maker: "arte noGja",price:76000,img:"https://random.imagecdn.app/500/150",status:true },
  ];
}
